/*
 Generated by typeshare 1.13.4
*/

export type AgentId = string;

export type ArtifactId = string;

export type CorrelationId = string;

export type GoalId = string;

export type ObservationId = string;

export type ResumeToken = string;

export type TaskId = string;

export type WakeId = string;

export enum StopReason {
	Responded = "Responded",
	Yielded = "Yielded",
	MaxStepsReached = "MaxStepsReached",
	DeadlineExceeded = "DeadlineExceeded",
	Cancelled = "Cancelled",
	ProviderFailure = "ProviderFailure",
	StorageFailure = "StorageFailure",
	PolicyAborted = "PolicyAborted",
	Suspended = "Suspended",
	Delegated = "Delegated",
}

export interface EngineOutcome {
	trigger_id: string;
	stop_reason: StopReason;
	response?: string;
	detail?: string;
	steps_executed: number;
	idempotent_replay: boolean;
	resume_token?: ResumeToken;
}

export type KernelEvent = 
	| { type: "GoalCreated", payload: GoalRecord }
	| { type: "TaskPlanned", payload: TaskRecord }
	| { type: "TaskClaimed", payload: {
	task_id: TaskId;
	claimed_at: string;
	assignee?: string;
}}
	| { type: "TaskBlocked", payload: {
	task_id: TaskId;
	blocked_at: string;
	reason: string;
}}
	| { type: "TaskCompleted", payload: {
	task_id: TaskId;
	completed_at: string;
	artifact_ids: ArtifactId[];
}}
	| { type: "TaskFailed", payload: {
	task_id: TaskId;
	failed_at: string;
	reason: string;
}}
	| { type: "TaskAbandoned", payload: {
	task_id: TaskId;
	abandoned_at: string;
	reason: string;
}}
	| { type: "HumanInputRequested", payload: {
	task_id?: TaskId;
	requested_at: string;
	prompt: string;
	resume_token: ResumeToken;
}}
	| { type: "ObservationAppended", payload: ObservationRecord }
	| { type: "ArtifactProduced", payload: ArtifactRecord }
	| { type: "WakeRequested", payload: WakeRequestRecord }
	| { type: "WakeScheduled", payload: WakeRequestRecord }
	| { type: "DelegationRequested", payload: DelegationRecord }
	| { type: "DelegationResolved", payload: {
	correlation_id: CorrelationId;
	resolved_at: string;
	payload: string;
	metadata: string;
}}
	| { type: "ResourceRegistered", payload: ResourceRef }
	| { type: "RelationshipObserved", payload: RelationshipEdge };

export interface KernelEventRecord {
	event_id: string;
	occurred_at: string;
	event: KernelEvent;
}

export interface AgentStateDelta {
	created_goal_ids: GoalId[];
	updated_task_ids: TaskId[];
	observation_ids: ObservationId[];
	artifact_ids: ArtifactId[];
	delegation_correlation_ids: CorrelationId[];
}

export interface WakeRequestRecord {
	wake_id: WakeId;
	requested_at: string;
	due_at: string;
	reason: string;
	task_id?: TaskId;
}

export interface AdvanceResult {
	outcome?: EngineOutcome;
	emitted_events: KernelEventRecord[];
	state_delta: AgentStateDelta;
	wake_request?: WakeRequestRecord;
}

export type SessionRecord = 
	| { type: "Trigger", payload: TriggerRecord }
	| { type: "KernelEvent", payload: KernelEventRecord }
	| { type: "ModelDecision", payload: ModelDecisionRecord }
	| { type: "Deliberation", payload: DeliberationRecord }
	| { type: "ToolExecutionGraph", payload: ToolExecutionGraph }
	| { type: "ToolNodeCheckpoint", payload: ToolNodeCheckpointRecord }
	| { type: "SkillInputValidation", payload: SkillInputValidationRecord }
	| { type: "ToolCall", payload: ToolCallRecord }
	| { type: "ToolResult", payload: ToolResultRecord }
	| { type: "PendingApproval", payload: PendingApprovalRecord }
	| { type: "ApprovalResolution", payload: ApprovalResolutionRecord }
	| { type: "Delegation", payload: DelegationRecord }
	| { type: "CoordinationClaim", payload: CoordinationClaimRecord }
	| { type: "ProviderUsage", payload: ProviderUsageRecord }
	| { type: "ProviderCache", payload: ProviderCacheRecord }
	| { type: "Reflection", payload: ReflectionRecord }
	| { type: "PolicyTuning", payload: PolicyTuningRecord }
	| { type: "StrategyPreference", payload: StrategyPreferenceRecord }
	| { type: "ToolPerformance", payload: ToolPerformanceRecord }
	| { type: "ProfilePatch", payload: ProfilePatchRecord }
	| { type: "Outcome", payload: OutcomeRecord };

export interface ToolResultRecord {
	call_id: string;
	finished_at: string;
	skill_name: string;
	output: Result<unknown, SkillFailure>;
}

export interface ToolRetryPolicy {
	max_retries: number;
	retry_backoff_ms: number;
}

export interface ToolDependency {
	call_id: string;
}

export interface ToolNode {
	call_id: string;
	skill_name: string;
	args: unknown;
	priority: number;
	dependencies: ToolDependency[];
	retry_policy: ToolRetryPolicy;
	dry_run: boolean;
	provider_order: number;
}

export interface ToolExecutionGraph {
	graph_id: string;
	trigger_id: string;
	step: number;
	created_at: string;
	nodes: ToolNode[];
}

export enum ToolNodeStatus {
	Queued = "Queued",
	Validated = "Validated",
	Started = "Started",
	Succeeded = "Succeeded",
	Failed = "Failed",
	Skipped = "Skipped",
	TimedOut = "TimedOut",
}

export interface ToolNodeCheckpointRecord {
	checkpoint_id: string;
	graph_id: string;
	call_id: string;
	skill_name: string;
	step: number;
	status: ToolNodeStatus;
	attempt: number;
	occurred_at: string;
	detail?: string;
}

export interface SkillInputValidationRecord {
	validation_id: string;
	graph_id: string;
	call_id: string;
	skill_name: string;
	validated_at: string;
	valid: boolean;
	errors: string[];
}

export enum DeliberationOutcome {
	NeedsRefinement = "NeedsRefinement",
	ReadyToAct = "ReadyToAct",
}

export interface DeliberationRecord {
	deliberation_id: string;
	trigger_id: string;
	step: number;
	created_at: string;
	summary: string;
	candidate_actions: string[];
	confidence: number;
	outcome: DeliberationOutcome;
}

export interface MemoryPolicy {
	max_recent_items: number;
	semantic_retrieval_limit: number;
	graph_hops: number;
}

export interface WakePolicy {
	allow_scheduled_wakes: boolean;
	default_recheck_ms: number;
	max_pending_wakes: number;
}

export interface ReviewPolicy {
	require_review_for_native_skills: boolean;
	require_review_for_delegation: boolean;
	reviewer_scopes: string[];
}

export interface EscalationPolicy {
	require_human_approval_scopes: string[];
	max_auto_delegations: number;
}

export interface AgentProfile {
	agent_id: AgentId;
	role: string;
	default_scopes: string[];
	allowed_skill_names: string[];
	goal_ids: GoalId[];
	memory_policy: MemoryPolicy;
	wake_policy: WakePolicy;
	review_policy: ReviewPolicy;
	escalation_policy: EscalationPolicy;
	config_artifact?: ArtifactId;
}

export enum GoalStatus {
	Active = "Active",
	Blocked = "Blocked",
	Completed = "Completed",
	Cancelled = "Cancelled",
}

export interface GoalRecord {
	goal_id: GoalId;
	created_at: string;
	title: string;
	detail?: string;
	status: GoalStatus;
	parent_goal_id?: GoalId;
}

export enum TaskStatus {
	Pending = "Pending",
	Ready = "Ready",
	Running = "Running",
	Blocked = "Blocked",
	WaitingHuman = "WaitingHuman",
	Done = "Done",
	Failed = "Failed",
	Abandoned = "Abandoned",
}

export interface TaskRecord {
	task_id: TaskId;
	goal_id?: GoalId;
	parent_task_id?: TaskId;
	created_at: string;
	title: string;
	detail?: string;
	status: TaskStatus;
	assignee?: string;
	blocked_by: TaskId[];
}

export interface ResourceRef {
	resource_id: string;
	resource_type: string;
	label: string;
	external_ref?: string;
}

export interface ObservationRecord {
	observation_id: ObservationId;
	recorded_at: string;
	source: string;
	content: string;
	attachment_ids: string[];
	related_resources: ResourceRef[];
}

export interface BlobDescriptor {
	uri: string;
	size_bytes: number;
}

export interface ArtifactRecord {
	artifact_id: ArtifactId;
	created_at: string;
	name: string;
	mime_type: string;
	descriptor?: BlobDescriptor;
	metadata: string;
}

export interface RelationshipEdge {
	from_resource_id: string;
	to_resource_id: string;
	relation: string;
	observed_at: string;
}

export interface AgentStateSnapshot {
	agent_id: AgentId;
	profile?: AgentProfile;
	goals: GoalRecord[];
	tasks: TaskRecord[];
	observations: ObservationRecord[];
	artifacts: ArtifactRecord[];
	resources: ResourceRef[];
	relationships: RelationshipEdge[];
	pending_wake?: WakeRequestRecord;
}

export interface AgentContextSnapshot {
	session_id: string;
	granted_scopes: string[];
	trigger_id: string;
	idempotency_key?: string;
	current_step: number;
	max_steps: number;
	history: SessionRecord[];
	prior_tool_results: ToolResultRecord[];
	session_cost_usd: number;
	state: AgentStateSnapshot;
}

export enum ApprovalDecision {
	Approved = "Approved",
	Rejected = "Rejected",
}

export interface ProviderRequestConfig {
	model?: string;
	temperature?: number;
	max_tokens?: number;
}

export interface EnginePolicy {
	max_steps: number;
	max_execution_time_ms: number;
	provider_timeout_ms: number;
	max_tool_timeout_ms: number;
	max_consecutive_tool_failures: number;
	cache_threshold_tokens: number;
	max_cost_per_session: number;
	max_parallel_skill_calls: number;
	max_inline_attachment_bytes: number;
	allow_native_skills: boolean;
	validate_tool_args: boolean;
	max_ready_tool_nodes: number;
	max_tool_retries_per_step: number;
	enable_tool_dry_run: boolean;
	self_improvement: SelfImprovementPolicy;
}

export interface ApprovalIngressRequest {
	session_id: string;
	resume_token: string;
	decision: ApprovalDecision;
	metadata?: unknown;
	granted_scopes?: BTreeSet<string>;
	provider?: ProviderRequestConfig;
	policy_override?: EnginePolicy;
}

export interface ApprovalResolutionRecord {
	resume_token: ResumeToken;
	resolved_at: string;
	decision: ApprovalDecision;
	metadata: unknown;
}

export type AttachmentContent = 
	| { type: "Inline", payload: {
	data: number[];
}}
	| { type: "Blob", payload: {
	descriptor: BlobDescriptor;
}};

export interface AttachmentRef {
	attachment_id: string;
	mime_type: string;
	file_name?: string;
	size_bytes: number;
	content: AttachmentContent;
}

export interface CoordinationClaimRecord {
	claim_id: string;
	trigger_key: string;
	claimed_at: string;
	expires_at: string;
}

export interface DelegationTarget {
	stream: string;
	worker?: string;
}

export interface DelegationTask {
	task_type: string;
	payload: unknown;
}

export interface DelegationRecord {
	correlation_id: CorrelationId;
	created_at: string;
	trigger_id: string;
	target: DelegationTarget;
	task: DelegationTask;
	resume_token: ResumeToken;
}

export interface DelegationResultIngressRequest {
	session_id: string;
	correlation_id: string;
	payload: unknown;
	metadata?: unknown;
	granted_scopes?: BTreeSet<string>;
	provider?: ProviderRequestConfig;
	policy_override?: EnginePolicy;
}

export interface MultimodalPayload {
	mime_type: string;
	file_name?: string;
	data: number[];
}

export interface EventIngressRequest {
	session_id: string;
	payload: unknown;
	attachments?: MultimodalPayload[];
	granted_scopes?: BTreeSet<string>;
	idempotency_key?: string;
	provider?: ProviderRequestConfig;
	policy_override?: EnginePolicy;
}

export interface HumanInputIngressRequest {
	session_id: string;
	content: string;
	attachments?: MultimodalPayload[];
	granted_scopes?: BTreeSet<string>;
	idempotency_key?: string;
	provider?: ProviderRequestConfig;
	policy_override?: EnginePolicy;
}

export type AgentAction = 
	| { type: "Plan", payload: {
	summary: string;
	candidate_actions: string[];
	confidence: number;
}}
	| { type: "Respond", payload: {
	content: string;
}}
	| { type: "CallSkills", payload: PlannedSkillCall[] }
	| { type: "Continue", payload: {
	reason: ContinueReason;
}}
	| { type: "Yield", payload: {
	reason?: string;
}}
	| { type: "Suspend", payload: {
	reason: SuspendReason;
	pending_calls: PlannedSkillCall[];
	resume_token: ResumeToken;
}}
	| { type: "Delegate", payload: {
	target: DelegationTarget;
	task: DelegationTask;
	correlation_id: CorrelationId;
	resume_token: ResumeToken;
}};

export interface ModelDecisionRecord {
	step: number;
	decided_at: string;
	action: AgentAction;
}

export enum SessionRecordKind {
	Trigger = "trigger",
	KernelEvent = "kernel_event",
	ModelDecision = "model_decision",
	Deliberation = "deliberation",
	ToolExecutionGraph = "tool_execution_graph",
	ToolNodeCheckpoint = "tool_node_checkpoint",
	SkillInputValidation = "skill_input_validation",
	ToolCall = "tool_call",
	ToolResult = "tool_result",
	PendingApproval = "pending_approval",
	ApprovalResolution = "approval_resolution",
	Delegation = "delegation",
	CoordinationClaim = "coordination_claim",
	ProviderUsage = "provider_usage",
	ProviderCache = "provider_cache",
	Reflection = "reflection",
	PolicyTuning = "policy_tuning",
	StrategyPreference = "strategy_preference",
	ToolPerformance = "tool_performance",
	ProfilePatch = "profile_patch",
	Outcome = "outcome",
}

export interface NewSessionRecord {
	session_id: string;
	occurred_at_ms: number;
	record_kind: SessionRecordKind;
	trigger_id?: string;
	idempotency_key?: string;
	record: SessionRecord;
}

export interface OutcomeRecord {
	trigger_id: string;
	idempotency_key?: string;
	finished_at: string;
	stop_reason: StopReason;
	response?: string;
	detail?: string;
	steps_executed: number;
	resume_token?: ResumeToken;
}

export type SuspendReason = 
	| { type: "HumanApprovalRequired", payload: {
	skill_names: string[];
}}
	| { type: "ProviderRequested", payload: {
	message: string;
}};

export interface PlannedSkillCall {
	call_id: string;
	name: string;
	args: unknown;
	priority: number;
	depends_on: string[];
	retry_policy: ToolRetryPolicy;
	dry_run: boolean;
}

export interface PendingApprovalRecord {
	resume_token: ResumeToken;
	created_at: string;
	trigger_id: string;
	step: number;
	reason: SuspendReason;
	pending_calls: PlannedSkillCall[];
}

export interface ProviderCacheRecord {
	provider_name: string;
	cached_content_id: string;
	token_count: number;
	cached_at: string;
}

export interface ProviderUsageRecord {
	provider_name: string;
	recorded_at: string;
	input_tokens: number;
	output_tokens: number;
	estimated_cost_usd: number;
	cached_content_id?: string;
}

export enum SelfImprovementMode {
	Advisory = "Advisory",
	AutoWithGuardrails = "AutoWithGuardrails",
}

export interface SelfImprovementPolicy {
	enabled: boolean;
	mode: SelfImprovementMode;
	reflection_interval_records: number;
	min_observations_before_tuning: number;
	max_policy_delta_percent: number;
	require_approval_for_scope_expansion: boolean;
	rollback_on_regression: boolean;
}

export interface PolicyOverlayPatch {
	max_steps?: number;
	max_execution_time_ms?: number;
	provider_timeout_ms?: number;
	max_tool_timeout_ms?: number;
	max_parallel_skill_calls?: number;
}

export enum PolicyOverlayStatus {
	Proposed = "Proposed",
	Applied = "Applied",
	RolledBack = "RolledBack",
	Rejected = "Rejected",
}

export interface PolicyOverlay {
	overlay_id: string;
	created_at: string;
	status: PolicyOverlayStatus;
	reason: string;
	evidence_window_records: number;
	patch: PolicyOverlayPatch;
	confidence: number;
	rollback_condition: string;
}

export enum PolicyTuningAction {
	Proposed = "Proposed",
	Applied = "Applied",
	RolledBack = "RolledBack",
	RejectedUnsafe = "RejectedUnsafe",
}

export interface ReflectionRecord {
	reflection_id: string;
	created_at: string;
	trigger_id: string;
	summary: string;
	observations: string[];
	confidence: number;
}

export interface PolicyTuningRecord {
	tuning_id: string;
	created_at: string;
	overlay: PolicyOverlay;
	action: PolicyTuningAction;
	prior_policy: EnginePolicy;
	projected_policy: EnginePolicy;
}

export interface StrategyPreferenceRecord {
	preference_id: string;
	created_at: string;
	skill_name?: string;
	preference: string;
	reason: string;
	confidence: number;
}

export interface ToolPerformanceRecord {
	performance_id: string;
	created_at: string;
	skill_name: string;
	backend_kind: string;
	calls: number;
	successes: number;
	failures: number;
	failure_rate: number;
}

export interface ProfilePatchRecord {
	patch_id: string;
	created_at: string;
	description: string;
	patch: unknown;
	requires_approval: boolean;
	applied: boolean;
}

export interface ProviderDecision {
	action: AgentAction;
	usage?: ProviderUsageRecord;
	cache?: ProviderCacheRecord;
}

export enum ProviderRole {
	System = "System",
	User = "User",
	Assistant = "Assistant",
	Tool = "Tool",
}

export type ProviderContentPart = 
	| { type: "Text", payload: string }
	| { type: "Json", payload: string }
	| { type: "InlineData", payload: MultimodalPayload }
	| { type: "Attachment", payload: AttachmentRef }
	| { type: "ToolResult", payload: ToolResultRecord };

export interface ProviderMessage {
	role: ProviderRole;
	parts: ProviderContentPart[];
}

export type AgentTrigger = 
	| { type: "ExternalEvent", payload: {
	source: string;
	payload: unknown;
	attachments: AttachmentRef[];
}}
	| { type: "ScheduledWake", payload: {
	wake_id: WakeId;
	due_at: string;
	reason: string;
}}
	| { type: "HumanInput", payload: {
	actor_id: string;
	content: string;
	attachments: AttachmentRef[];
}}
	| { type: "SystemObservation", payload: {
	source: string;
	observation: unknown;
	attachments: AttachmentRef[];
}}
	| { type: "Webhook", payload: {
	source: string;
	payload: unknown;
	attachments: AttachmentRef[];
}}
	| { type: "RuleTrigger", payload: {
	rule_id: string;
	context: unknown;
	attachments: AttachmentRef[];
}}
	| { type: "ProactiveHeartbeat", payload: {
	timestamp: number;
	attachments: AttachmentRef[];
}}
	| { type: "Message", payload: {
	user_id: string;
	content: string;
	attachments: AttachmentRef[];
}}
	| { type: "Approval", payload: {
	resume_token: ResumeToken;
	decision: ApprovalDecision;
	metadata: unknown;
}}
	| { type: "DelegationResult", payload: {
	correlation_id: CorrelationId;
	payload: unknown;
	metadata: unknown;
}};

export type SkillCapability = 
	| { type: "KeyValueRead", payload: {
	namespaces: string[];
}}
	| { type: "HttpOutbound", payload: {
	allow_hosts: string[];
}}
	| { type: "StructuredLog", payload?: undefined };

export interface ResourcePolicy {
	timeout_ms: number;
	max_memory_bytes: number;
	max_fuel?: number;
	priority_class: number;
	max_retries: number;
	retry_backoff_ms: number;
	dry_run_supported: boolean;
}

export interface SkillManifest {
	name: string;
	description: string;
	input_schema: unknown;
	required_scopes: string[];
	capability_grants: SkillCapability[];
	resource_policy: ResourcePolicy;
	approval_required: boolean;
}

export interface SkillDefinition {
	manifest: SkillManifest;
	executor_kind: string;
}

export interface ProviderRequest {
	trigger: AgentTrigger;
	context: AgentContextSnapshot;
	available_skills: SkillDefinition[];
	config: ProviderRequestConfig;
	policy: EnginePolicy;
	contents: ProviderMessage[];
}

export interface StoredSessionRecord {
	session_id: string;
	sequence_no: number;
	occurred_at_ms: number;
	record_kind: SessionRecordKind;
	trigger_id?: string;
	idempotency_key?: string;
	record: SessionRecord;
}

export interface RecordPage {
	session_id: string;
	records: StoredSessionRecord[];
	next_offset?: number;
}

export interface RecordPageQuery {
	session_id: string;
	offset: number;
	limit: number;
	since_ms?: number;
	until_ms?: number;
}

export interface RuntimeServerConfig {
	bind_address: SocketAddr;
	request_timeout_ms: number;
	default_policy: EnginePolicy;
	allow_policy_overrides: boolean;
	allow_provider_overrides: boolean;
	default_provider: ProviderRequestConfig;
}

export type StoreBootstrapConfig = 
	| { type: "in_memory", payload?: undefined }
	| { type: "sqlite", payload: {
	database_url: string;
}}
	| { type: "postgres", payload: {
	database_url: string;
}};

export type ProviderBootstrapConfig = 
	| { type: "mock", payload: {
	response: string;
}}
	| { type: "open_ai_compatible", payload: {
	base_url: string;
	api_key: string;
	model: string;
	temperature?: number;
	max_tokens?: number;
	system_prompt: string;
}}
	| { type: "gemini", payload: {
	base_url: string;
	auth_mode: GeminiAuthMode;
	credential: string;
	model: string;
	temperature?: number;
	max_tokens?: number;
	system_instruction: string;
	provider_name: string;
}};

export interface RuntimeBootstrapConfig {
	server: RuntimeServerConfig;
	store: StoreBootstrapConfig;
	blob: BlobBootstrapConfig;
	provider: ProviderBootstrapConfig;
}

export interface RuntimeRunResult {
	advances: AdvanceResult[];
	outcome: EngineOutcome;
}

export interface ScheduledWakeIngressRequest {
	session_id: string;
	wake_id: string;
	due_at: string;
	reason: string;
	granted_scopes?: BTreeSet<string>;
	provider?: ProviderRequestConfig;
	policy_override?: EnginePolicy;
}

export interface SessionListQuery {
	offset: number;
	limit: number;
	since_ms?: number;
	until_ms?: number;
}

export interface SessionSnapshot {
	session_id: string;
	records: SessionRecord[];
	last_sequence_no?: number;
	latest_outcome?: OutcomeRecord;
}

export interface SessionSummary {
	session_id: string;
	first_recorded_at_ms: number;
	last_recorded_at_ms: number;
	record_count: number;
}

export enum SkillFailureKind {
	PermissionDenied = "PermissionDenied",
	CapabilityDenied = "CapabilityDenied",
	Timeout = "Timeout",
	MemoryLimitExceeded = "MemoryLimitExceeded",
	Trap = "Trap",
	InvalidResponse = "InvalidResponse",
	Internal = "Internal",
}

export interface SkillFailure {
	kind: SkillFailureKind;
	message: string;
}

export interface SkillInvocation {
	call_id: string;
	manifest: SkillManifest;
	args: unknown;
	context: AgentContextSnapshot;
}

export enum SkillBackendKind {
	Wasm = "wasm",
	Native = "native",
}

export interface ToolCallRecord {
	call_id: string;
	step: number;
	called_at: string;
	skill_name: string;
	args: unknown;
	backend_kind: SkillBackendKind;
}

export interface TriggerRecord {
	trigger_id: string;
	session_id: string;
	idempotency_key?: string;
	recorded_at: string;
	trigger: AgentTrigger;
}

export interface WebhookIngressRequest {
	session_id: string;
	payload: unknown;
	attachments?: MultimodalPayload[];
	granted_scopes?: BTreeSet<string>;
	idempotency_key?: string;
	provider?: ProviderRequestConfig;
	policy_override?: EnginePolicy;
}

export enum ContinueReason {
	ToolResultAppended = "ToolResultAppended",
	ModelRequested = "ModelRequested",
}

export enum GeminiAuthMode {
	ApiKey = "api_key",
	BearerToken = "bearer_token",
}


// Automatically injected wrapper types
export type Result<T, E> = { Ok: T } | { Err: E };
export type BTreeSet<T> = T[];
export type SocketAddr = string;

export type BlobBootstrapConfig = 
  | { type: "InMemory" }
  | { type: "LocalDirectory", payload: { path: string } }
  | { type: "S3", payload: { bucket: string, region?: string } }
  | { type: "Gcs", payload: { bucket: string } };
